[fix] MeasureSpotsFocus() only worked with specific dtypes
MeasureSpotsFocus() uses OpenCV functions, which only support some
specific dtypes. In particular, they don't handle uint32, which some
detectors generates.

In such case, this error happens (during autofocus):
File "/usr/lib/python3/dist-packages/odemis/util/focus.py", line 123, in MeasureSpotsFocus
    sobelx = cv2.Sobel(image, cv2.CV_64F, 1, 0, ksize=5)
cv2.error: OpenCV(4.5.4) :-1: error: (-5:Bad argument) in function 'Sobel'
> Overload resolution failed:
>  - src data type = 6 is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'

=> Detect the image dtype is not supported and convert to float64 before
calling OpenCV.

Do the same with MeasureOpticalFocus(), as it also relies on OpenCV.