[fix] gui PlotCanvas: handle corner cases when data changes outside of the range
If the data changes to an entirely different, while the user had zoomed
in a single value, the display of the plot would not work anymore... and
it would not be possible to zoom out.

=> Check that the range of the display is always within the range of the
data, and if not adjust it.

This caused errors like:
File "/home/piel/development/odemis/src/odemis/gui/comp/miccanvas.py", line 1459, in on_size
self.refresh_plot()
File "/home/piel/development/odemis/src/odemis/util/__init__.py", line 589, in limit
return f(self, *args, **kwargs)
File "/home/piel/development/odemis/src/odemis/gui/comp/miccanvas.py", line 1424, in refresh_plot
ys = [yst[lox]]
IndexError: index 1328 is out of bounds for axis 0 with size 1328