[fix] GUI METEOR: handle streams with an empty name
Odemis tries to provide a list of the last streams created previously.
However, if one stream was created with an empty name (""), that empty
label would end up confusing wx.MenuItem(), showing such error:
  File "/home/piel/development/odemis/src/odemis/gui/cont/stream_bar.py", line 128, in __init__
    self._createAddStreamActions()
  File "/home/piel/development/odemis/src/odemis/gui/cont/stream_bar.py", line 1289, in _createAddStreamActions
    self.add_action(label, call_label, fluor_capable)
  File "/home/piel/development/odemis/src/odemis/gui/cont/stream_bar.py", line 192, in add_action
    self._stream_bar.btn_add_stream.add_choice(title, callback, check_enabled)
  File "/home/piel/development/odemis/src/odemis/gui/comp/buttons.py", line 1057, in add_choice
    menu_item = wx.MenuItem(self.menu, menu_id, label)
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at /tmp/pip-install-eoie9qdr/wxpython_1b4ae2e90f734464912c8577e97b58ec/ext/wxWidgets/src/common/stockitem.cpp(219) in wxGet
StockLabel(): invalid stock item ID

=> Detect such case and replace by a generic (but unique) name.

Also detect that PopupImageButton.add_choice() was called with an empty
label, and raise a less confusing error. That will save some time next
time.

Also detect PopupImageButton.add_choice() is called with an existing
label, as it's also causes issues (and allowing it would be confusing for the user).