gui model: give clear error messages when a required component is missing
For the SECOM/SPARC/DELPHI, we have some basic expectations in the code
in terms of which component has to be present.

So far, if the user doesn't have this component in the microscope file
(or, more likely, the component role has a typo), very unclear messages
are shown, such as:
2021-06-04 10:44:24,114	ERROR	main:381:	Traceback (most recent call last):
  File "/home/cryo-poc/development/odemis/src/odemis/gui/main.py", line 140, in OnInit
    self.init_gui()
  File "/home/cryo-poc/development/odemis/src/odemis/gui/main.py", line 237, in init_gui
    self.tab_controller = tabs.TabBarController(tab_defs, self.main_frame, self.main_data)
  File "/home/cryo-poc/development/odemis/src/odemis/gui/cont/tabs.py", line 5433, in __init__
    tab_list, default_tab = self._create_needed_tabs(tab_defs, main_frame, main_data)
  File "/home/cryo-poc/development/odemis/src/odemis/gui/cont/tabs.py", line 5509, in _create_needed_tabs
    tpnl, main_frame, main_data)
  File "/home/cryo-poc/development/odemis/src/odemis/gui/cont/tabs.py", line 3322, in __init__
    hwemtvas=get_local_vas(main_data.ebeam, main_data.hw_settings_config),
  File "/home/cryo-poc/development/odemis/src/odemis/gui/conf/data.py", line 936, in get_local_vas
    config_vas = get_hw_config(hw_comp, hw_settings)
  File "/home/cryo-poc/development/odemis/src/odemis/gui/conf/data.py", line 894, in get_hw_config
    role = hw_comp.role
AttributeError: 'NoneType' object has no attribute 'role'

It would now show:
KeyError: Microscope (secom) is missing the 'e-beam' component

Also add test cases for the gui.model.MainGUIData.