[config] Add milling_task.yaml to the files to package
This is used as the default milling configuration. Without this file,
the METEOR GUI fails to load with such error:
2025-07-21 10:25:12,283	ERROR	main:422:	Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odemis/gui/main.py", line 152, in OnInit
    self.init_gui()
  File "/usr/lib/python3/dist-packages/odemis/gui/main.py", line 279, in init_gui
    self.tab_controller = tabs.TabBarController(tab_defs, self.main_frame, self.main_data)
  File "/usr/lib/python3/dist-packages/odemis/gui/cont/tabs/tab_bar_controller.py", line 150, in __init__
    tab_list, default_tab = self._create_needed_tabs(tab_defs, main_frame, main_data)
  File "/usr/lib/python3/dist-packages/odemis/gui/cont/tabs/tab_bar_controller.py", line 180, in _create_needed_tabs
    tab = tab_def["controller"](tab_def["name"], tab_def["button"],
  File "/usr/lib/python3/dist-packages/odemis/gui/cont/tabs/fibsem_tab.py", line 202, in __init__
    self.milling_task_controller = milling.MillingTaskController(tab_data, panel, self)
  File "/usr/lib/python3/dist-packages/odemis/gui/cont/milling.py", line 158, in __init__
    self.milling_tasks = load_milling_tasks(MILLING_TASKS_PATH) # TODO: move to main_data
  File "/usr/lib/python3/dist-packages/odemis/acq/milling/tasks.py", line 126, in load_milling_tasks
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/odemis/acq/milling/milling_tasks.yaml'