[fix] SPARC acquisition with spectrum stream would sometimes fail
The check for the presence of the light component was incorrect, causing
the acquisition to fail in some configurations.
Solves such error:
2026-02-18 14:26:48,529  ERROR   _sync:1331 Software sync acquisition of multiple detectors failed
Traceback (most recent call last):
  File "/home/piel/development/odemis/src/odemis/acq/stream/_sync.py", line 1285, in _run_acquisition_ccd
    self._run_leeches(acquirer, pixel_das)
  File "/home/piel/development/odemis/src/odemis/acq/stream/_sync.py", line 1124, in _run_leeches
    acquirer.resume_pixel_acquisition()
  File "/home/piel/development/odemis/src/odemis/acq/stream/_sync.py", line 3179, in resume_pixel_acquisition
    if hasattr(self._mdstream._sccd, "light") and self._mdstream._sccd.light.value:
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'