gui comp stream: fix changing stream tint on wxPython4
wxPython4 has a small behaviour difference compared to wxPython3: wxColour.Get()
returns by default also the alpha value. So this is a 4-tuple.
=> explicitely indicate we don't want the alpha value.

That prevented the stream tint from changing, when using wxpython 4,
generating such errors:

ERROR   log:41: Updating RGBSpatialProjection CL intensity image
Traceback (most recent call last):
  File "/home/piel/development/odemis/src/odemis/acq/stream/_projection.py", line 518, in _updateImage
    self._raw, projected_tiles = self._getTilesFromSelectedArea()
  File "/home/piel/development/odemis/src/odemis/acq/stream/_projection.py", line 494, in _getTilesFromSelectedArea
    self._getTile(x, y, z, prev_raw_cache, prev_proj_cache)
  File "/home/piel/development/odemis/src/odemis/acq/stream/_projection.py", line 405, in _getTile
    proj_tile = self._projectTile(raw_tile)
  File "/home/piel/development/odemis/src/odemis/acq/stream/_projection.py", line 435, in _projectTile
    return self._projectXY2RGB(tile, self.stream.tint.value)
  File "/home/piel/development/odemis/src/odemis/acq/stream/_projection.py", line 295, in _projectXY2RGB
    rgbim = img.DataArray2RGB(data, irange, tint)
  File "/home/piel/development/odemis/src/odemis/util/img.py", line 378, in DataArray2RGB
    rtint, gtint, btint = tint
ValueError: too many values to unpack