[fix] IndependentEBICStream potentially leaving the detectors active after pause
There is a potential threading race condition, when stopping the stream,
while at exactly in that moment it's restarting the acquisition. In this
case, one or both detectors could be left active.
=> lock the sections to avoid them being run concurrently.

Also fix SPARC2TestCaseIndependentDetector.test_ebic_live_stream failure

Tests expects that no data is generated after stopping the live stream,
however, it might take a tiny bit of time for projection to be run (in the
background), so 1 or 2 images could be generated extra.
=> Wait a bit before checking the stream doesn't generate data.

Fixes this failure:
======================================================================
FAIL: test_ebic_live_stream (__main__.SPARC2TestCaseIndependentDetector)
Test live IndependentEBICStream, and especially, that it can provide continuous
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/piel/development/odemis/src/odemis/acq/test/stream_test.py", line 4069, in test_ebic_live_stream
    self.assertEqual(nb_images, len(self._images), "EBIC images received after stopping live stream")
AssertionError: 40 != 42 : EBIC images received after stopping live stream

----------------------------------------------------------------------
Ran 1 test in 20.930s

FAILED (failures=1)