[fix] util driver use the requested axis instead of always taking z
[refactor] util driver: simplify calculation of estimateMoveDuration
Simplify the calculation of estimateMoveDuration, add explanations on the calculation and add test cases.

Raise a ValueError when the input distance is not a negative value, to prevent the following error in the time estimation calculation:
  File "/home/patel/development/odemis/src/odemis/util/driver.py", line 145, in estimateMoveDuration
    vp = math.sqrt(2.0 * distance / A)
ValueError: math domain error```