[fix] rasied TypeError by passing default colour value during FastEMROC class init (#2543)
TypeError: __init__() missing 1 required positional argument: 'colour'