acq path: don't raise error if changing CCD fan speed fails
It's annoying, but not a reason to stop an acquisition, or prevent closing
the window (because it tries to turn on the CCD fan again on close).

This happened in a couple of cases on the SECOM, when the CCD image was playing
in the background. In such case, the Zyla doesn't accept changing the fan speed,
and the function fail with such error:
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 16765, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/lib/python2.7/dist-packages/odemis/gui/win/acquisition.py", line 529, in on_acquisition_done
    self._main_data_model.opm.setAcqQuality(path.ACQ_QUALITY_FAST)
  File "/usr/lib/python2.7/dist-packages/odemis/acq/path.py", line 439, in setAcqQuality
    self._setCCDFan(True)
  File "/usr/lib/python2.7/dist-packages/odemis/acq/path.py", line 843, in _setCCDFan
    temp.value = min(comp.targetTemperature.value, self._enabled_fan_temp)
  File "/usr/lib/python2.7/dist-packages/odemis/model/_vattributes.py", line 361, in value
    return self.__getattr__("_set_value")(v)
  File "/usr/lib/python2.7/dist-packages/Pyro4/core.py", line 165, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/Pyro4/core.py", line 333, in _pyroInvoke
    raise data
ATError: Call to AT_SetBool failed with error code 5: ERR_NOTWRITABLE (Feature is currently not writable)
Remote exception Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Pyro4/core.py", line 911, in handleRequest
    data=method(*vargs, **kwargs)   # this is the actual method call to the Pyro object
  File "/usr/lib/python2.7/dist-packages/odemis/model/_vattributes.py", line 202, in _set_value
    self._value = self._setter(value)
  File "/usr/lib/python2.7/dist-packages/odemis/util/weak.py", line 37, in __call__
    return self.f(ins, *arg, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odemis/driver/andorcam3.py", line 863, in setTargetTemperature
    self.SetBool(u"SensorCooling", True)
  File "/usr/lib/python2.7/dist-packages/odemis/driver/andorcam3.py", line 711, in SetBool
    self.atcore.AT_SetBool(self.handle, prop, int_val)
  File "/usr/lib/python2.7/dist-packages/odemis/driver/andorcam3.py", line 112, in at_errcheck
    (str(func.__name__), result, ATDLL.err_code[result]))
ATError: Call to AT_SetBool failed with error code 5: ERR_NOTWRITABLE (Feature is currently not writable)