[fix] Technolution convert phase shift to int
To shift the setpoints by a shift-factor the numpy array is rolled by that factor multiplied by the number of setpoints.
`round` was used to convert to an integer value to roll by, however in old versions of python/numpy round can return a float instead of an int, this could lead to numpy.roll failing with the error

TypeError: slice indices must be integers or None or have an __index__ method