[fix] the test cases in z_localization_test.py
Due to use of a function, no longer in use
E   ImportError: cannot import name 'measure_z' from 'odemis.acq.align.z_localization' (/home/testing/development/odemis/src/odemis/acq/align/z_localization.py)