[fix] raise ValueError for incompatible TIFF writes
The exporter expects a rectangular numeric NumPy array (e.g. uint16, with consistent Z/Y/X dimensions); a ragged Z-stack can produce dtype=object, which then during TIFFWriteDirectory() returns 0, the wrapper raises AssertionError: 0. This fix improves the logging of the data shape when an exception is raised during acquisition and improves the error logging during the writing of the tiff image.

The original error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odemis/acq/acqmng.py", line 221, in run
    data, exp = self._single_acqui_f.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3/dist-packages/odemis/util/__init__.py", line 843, in bindFuture
    result = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odemis/acq/acqmng.py", line 565, in run
    das, acq_exp = f.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3/dist-packages/odemis/util/__init__.py", line 843, in bindFuture
    result = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odemis/acq/_futures.py", line 115, in _run
    raise IOError("Acquisition of stream %s timed out after %f s" %
OSError: Acquisition of stream JFX650 timed out after 11.834785 s
2026-02-05 16:01:26,111	DEBUG	futures:236:	Created future <ClientFuture at 0x75f404772ef0 for Proxy of Component 'Optical Focus'>
2026-02-05 16:01:26,111	DEBUG	core:306:	Going to send client future PYRO:obj_734cad81755a4ace80815c1f522d7523@localhost:46613
2026-02-05 16:01:26,113	INFO	cryo_acq:341:	The acquisition is done
2026-02-05 16:01:26,113	ERROR	cryo_acq:353:	Acquisition partially failed Acquisition of stream JFX650 timed out after 11.834785 s:
2026-02-05 16:01:26,132	DEBUG	threadpoolserver:132:	connected ('127.0.0.1', 44884)
2026-02-05 16:01:26,134	DEBUG	futures:374:	Unregistered future <ClientFuture at 0x75f404772ef0 for Proxy of Component 'Optical Focus'>
2026-02-05 16:01:26,134	DEBUG	threadpoolserver:35:	disconnected ('127.0.0.1', 44884)
2026-02-05 16:01:26,141	DEBUG	tiff:1358:	found 1 image groups for 1 data arrays. groups: dict_keys([0])
2026-02-05 16:01:26,141	DEBUG	tiff:1703:	Will scan the dimension ['T', 'Z', 'C'] of size [1, 41, 1]
2026-02-05 16:01:26,144	DEBUG	tiff:1358:	found 1 image groups for 1 data arrays. groups: dict_keys([0])
2026-02-05 16:01:26,144	DEBUG	tiff:179:	Metadata tag 'Software version' skipped when saving TIFF metadata
2026-02-05 16:01:26,144	DEBUG	tiff:179:	Metadata tag 'Detector type' skipped when saving TIFF metadata
2026-02-05 16:01:26,144	DEBUG	tiff:179:	Metadata tag 'Sensor size' skipped when saving TIFF metadata
2026-02-05 16:01:26,144	DEBUG	tiff:179:	Metadata tag 'Sensor pixel size' skipped when saving TIFF metadata
2026-02-05 16:01:26,144	DEBUG	tiff:179:	Metadata tag 'Sensor temperature' skipped when saving TIFF metadata
2026-02-05 16:01:26,145	DEBUG	tiff:179:	Metadata tag 'Data filter' skipped when saving TIFF metadata
2026-02-05 16:01:26,145	DEBUG	tiff:179:	Metadata tag 'Lens name' skipped when saving TIFF metadata
2026-02-05 16:01:26,145	DEBUG	tiff:179:	Metadata tag 'Lens magnification' skipped when saving TIFF metadata
2026-02-05 16:01:26,145	DEBUG	tiff:179:	Metadata tag 'Binning' skipped when saving TIFF metadata
2026-02-05 16:01:26,145	DEBUG	tiff:179:	Metadata tag 'Lens numerical aperture' skipped when saving TIFF metadata
2026-02-05 16:01:26,145	DEBUG	tiff:179:	Metadata tag 'Lens refractive index' skipped when saving TIFF metadata
2026-02-05 16:01:26,145	DEBUG	tiff:179:	Metadata tag 'Input wavelength range' skipped when saving TIFF metadata
2026-02-05 16:01:26,145	DEBUG	tiff:179:	Metadata tag 'Light power' skipped when saving TIFF metadata
2026-02-05 16:01:26,145	DEBUG	tiff:179:	Metadata tag 'Output wavelength range' skipped when saving TIFF metadata
2026-02-05 16:01:26,146	DEBUG	tiff:179:	Metadata tag 'Stage position raw' skipped when saving TIFF metadata
2026-02-05 16:01:26,146	DEBUG	tiff:179:	Metadata tag 'Gain' skipped when saving TIFF metadata
2026-02-05 16:01:26,146	DEBUG	tiff:179:	Metadata tag 'Pixel readout time' skipped when saving TIFF metadata
2026-02-05 16:01:26,146	DEBUG	tiff:179:	Metadata tag 'Exposure time' skipped when saving TIFF metadata
2026-02-05 16:01:26,146	DEBUG	tiff:179:	Metadata tag 'Bits per pixel' skipped when saving TIFF metadata
2026-02-05 16:01:26,146	DEBUG	tiff:179:	Metadata tag 'Baseline value' skipped when saving TIFF metadata
2026-02-05 16:01:26,146	DEBUG	tiff:179:	Metadata tag 'Acquisition type' skipped when saving TIFF metadata
2026-02-05 16:01:26,146	DEBUG	tiff:179:	Metadata tag 'Display tint' skipped when saving TIFF metadata
2026-02-05 16:01:26,147	DEBUG	tiff:179:	Metadata tag 'Extra settings' skipped when saving TIFF metadata
2026-02-05 16:01:26,147	DEBUG	tiff:179:	Metadata tag 'Dimension names' skipped when saving TIFF metadata
2026-02-05 16:01:26,191	DEBUG	slider:451:	Identical value 0.015 ignored
2026-02-05 16:01:26,191	DEBUG	slider:587:	Updating number field from 0.015 to 0.015
2026-02-05 16:01:26,191	DEBUG	slider:451:	Identical value 0.01 ignored
2026-02-05 16:01:26,191	DEBUG	slider:587:	Updating number field from 0.01 to 0.01
2026-02-05 16:01:26,192	DEBUG	slider:451:	Identical value 0.39 ignored
2026-02-05 16:01:26,192	DEBUG	slider:587:	Updating number field from 0.39 to 0.39
2026-02-05 16:01:26,192	DEBUG	slider:776:	Setting range to 0, 11519
2026-02-05 16:01:26,195	DEBUG	slider:451:	Identical value 0.12213759295866246 ignored
2026-02-05 16:01:26,195	DEBUG	slider:587:	Updating number field from 0.12213759295866246 to 0.12213759295866246
2026-02-05 16:01:26,195	DEBUG	slider:451:	Identical value 0.13518780614246453 ignored
2026-02-05 16:01:26,195	DEBUG	slider:587:	Updating number field from 0.13518780614246453 to 0.13518780614246453
2026-02-05 16:01:26,196	DEBUG	slider:451:	Identical value 0.390625 ignored
2026-02-05 16:01:26,196	DEBUG	slider:587:	Updating number field from 0.390625 to 0.390625
2026-02-05 16:01:26,198	DEBUG	slider:451:	Identical value 0.12307790700187436 ignored
2026-02-05 16:01:26,199	DEBUG	slider:587:	Updating number field from 0.12307790700187436 to 0.12307790700187436
2026-02-05 16:01:26,199	DEBUG	slider:451:	Identical value 0.5415354852465448 ignored
2026-02-05 16:01:26,199	DEBUG	slider:587:	Updating number field from 0.5415354852465448 to 0.5415354852465448
2026-02-05 16:01:26,199	DEBUG	slider:451:	Identical value 0.13 ignored
2026-02-05 16:01:26,199	DEBUG	slider:587:	Updating number field from 0.13 to 0.13
2026-02-05 16:01:26,202	DEBUG	slider:451:	Identical value 0.1 ignored
2026-02-05 16:01:26,202	DEBUG	slider:587:	Updating number field from 0.1 to 0.1
2026-02-05 16:01:26,202	DEBUG	slider:451:	Identical value 0.5 ignored
2026-02-05 16:01:26,202	DEBUG	slider:587:	Updating number field from 0.5 to 0.5
2026-02-05 16:01:26,203	DEBUG	slider:451:	Identical value 0.010238075241854529 ignored
2026-02-05 16:01:26,203	DEBUG	slider:587:	Updating number field from 0.010238075241854529 to 0.010238075241854529
2026-02-05 16:01:26,566	DEBUG	file:93:	Writing configuration file '/home/meteor/.config/odemis/acquisition.config'
2026-02-05 16:01:26,568	DEBUG	file:93:	Writing configuration file '/home/meteor/.config/odemis/acquisition.config'
2026-02-05 16:01:26,575	ERROR	main:422:	Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wx/core.py", line 3282, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/usr/lib/python3/dist-packages/odemis/gui/cont/acquisition/cryo_acq.py", line 504, in _on_export_data_done
    data = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/odemis/gui/cont/acquisition/cryo_acq.py", line 548, in _export_data
    exporter.export(filename, data, thumb_nail)
  File "/usr/lib/python3/dist-packages/odemis/dataio/tiff.py", line 2260, in export
    _saveAsMultiTiffLT(filename, data, thumbnail, compressed, pyramid=pyramid, imagej=imagej)
  File "/usr/lib/python3/dist-packages/odemis/dataio/tiff.py", line 2099, in _saveAsMultiTiffLT
    write_image(f, data[i], write_rgb=write_rgb, compression=c, pyramid=pyramid)
  File "/usr/lib/python3/dist-packages/odemis/dataio/tiff.py", line 2185, in write_image
    f.write_image(arr, compression=compression, write_rgb=write_rgb)
  File "/usr/lib/python3/dist-packages/libtiff/libtiff_ctypes.py", line 679, in write_image
    self.WriteDirectory()
  File "/usr/lib/python3/dist-packages/libtiff/libtiff_ctypes.py", line 1145, in WriteDirectory
    assert r == 1, repr(r)
AssertionError: 0
2026-02-05 16:01:27,492	DEBUG	log:230:	Reporting error in Camera: Camera disconnected
2026-02-05 16:01:27,524	DEBUG	popup:56:	Notification: Error in Camera. Camera disconnected