[fix] test_cryo_feature_overlay in comp_overlay_test.py by mocking the backend components used in posture manager which is called by cryo_feature.py comp_overlay_test.py:501: in test_cryo_feature_overlay     cryofeature_overlay = CryoFeatureOverlay(cnvs, tab_mod) ../comp/overlay/cryo_feature.py:60: in __init__     self.view_posture = self.tab_data.view_posture.value E   AttributeError: 'CryoGUIData' object has no attribute 'view_posture'