[FIX] Meteor overview imaging failed to start
Commit ca419d9a changed the overview imaging interface if multiple grids were available. To do this it added an attribute self._grids if multiple grids were avalable.
This attribute was always called at the start and at the beginning of an overview image, causing the overview imaging to fail on the Meteor. With the error:

2023-06-28 10:45:11,426 ERROR   main:414:       Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wx/core.py", line 3285, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/pals/development/odemis/src/odemis/gui/win/acquisition.py", line 1295, in on_acquisition_done
    self._resume_settings()
  File "/home/pals/development/odemis/src/odemis/gui/win/acquisition.py", line 1167, in _resume_settings
    self._on_whole_grid_chkbox()
  File "/home/pals/development/odemis/src/odemis/gui/win/acquisition.py", line 981, in _on_whole_grid_chkbox
    self._grids.Enable(whole_grid)
AttributeError: 'OverviewAcquisitionDialog' object has no attribute '_grids'

This fix only calls self._grids when it is not None.