[fix] enzel stream controller: on_stream_panel_destroy did not require an input argument
Commit b075a230a3aa00c725ce2ee3de74a325aa12e888 removed the input argument of StreamController._on_stream_panel_destroy() but the caller in tabs.py for Enzel was not updated. The following error was raised:

13:17:13 ERROR   main           : Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wx/core.py", line 3282, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/delmic_new/development/odemis/src/odemis/gui/cont/tabs.py", line 5131, in _set_top_and_bottom_stream_and_settings
    stream_controller._on_stream_panel_destroy(None)
TypeError: StreamController._on_stream_panel_destroy() takes 1 positional argument but 2 were given