[fix] on enzel only remove the stream if it had not been removed already
During Ubuntu 22.04 testing we got the following error:

0x7f8c6c191780> raised exception when receiving value <odemis.acq.feature.CryoFeature object at 0x7f8c446a9060>
Traceback (most recent call last):
  File "/home/delmic_new/development/odemis/src/odemis/model/_vattributes.py", line 96, in notify
    l(v)
  File "/home/delmic_new/development/odemis/src/odemis/util/weak.py", line 36, in __call__
    return self.f(ins, *arg, **kwargs)
  File "/home/delmic_new/development/odemis/src/odemis/gui/cont/streams.py", line 3302, in _on_current_feature_changes
    self.clear_feature_streams()
  File "/home/delmic_new/development/odemis/src/odemis/gui/cont/streams.py", line 3326, in clear_feature_streams
    self.stream_controllers.remove(sc)
ValueError: list.remove(x): x not in list