gui legend: support calling .redraw() while .pain() is called
This can happen when the selectionWidth changes as it's called in a separate thread.

It would cause errors like that:
2015-01-19 13:43:42,787 DEBUG   legend:370: Setting first tick at value 200.0
2015-01-19 13:43:42,791 ERROR   main:274: Traceback (most recent call last):
  File "/home/piel/development/odemis/src/odemis/gui/comp/legend.py", line 291, in on_paint
    self.calc_ticks(ctx)
  File "/home/piel/development/odemis/src/odemis/gui/comp/legend.py", line 376, in calc_ticks
    if (pos, tick) not in self.ticks:
TypeError: argument of type 'NoneType' is not iterable