[fix] tabs: pass an integer instead of a float to the start method of the pulse timer
In ubuntu 22.04 the start of method of the timer requires you pass an integer instead of a float, the following error was raised

11:33:30 ERROR   main           : Traceback (most recent call last):
  File "/home/delmic_new/development/odemis/src/odemis/gui/cont/tabs.py", line 2421, in _on_switch_btn
    self._pulse_timer.Start(250.0)  # 4 Hz
TypeError: Timer.Start(): argument 1 has unexpected type 'float'