[fix] TestIndependentDetector.test_dwell_time() failure
Need to use "almost equal" on float.

Fixes this failure:
======================================================================
FAIL: test_dwell_time (__main__.TestIndependentDetector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/piel/development/odemis/src/odemis/driver/test/simsem_test.py", line 554, in test_dwell_time
    self.assertEqual(self.det.dwellTime.value, 10e-6)
AssertionError: 9.999999999999999e-06 != 1e-05