[fix] rasied TypeError by passing default colour value during FastEMROC class init
TypeError: __init__() missing 1 required positional argument: 'colour'