model vattributes: in case the value is reject due to its type, indicate the type
On Windows, we sometimes get errors like:
TypeError: Value '(5.615522460937501e-07, 6.356466064453125e-07)' must be a tuple only consisting of types (<class 'int'>, <class 'int'>, <class 'float'>).

It's extrermly hard to reproduce, and this has been going on for a year, with little extra findings.
Hopefully this information will hint us a little bit more.