gui cont tabs: don't try to display CLStreams on the line spectrum viewport
It's not very clear why we ever added CLStream to that viewport, but I'd suspect
that it's because it was confusingly called "Spatial spectrum".
Now that the view uses a projection, the projection fails (before the viewport
would just silently not even try to show the data). It would cause such error:
2019-03-07 09:06:06,409 ERROR   main:375: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wxPython-4.0.4-py2.7-linux-x86_64.egg/wx/core.py", line 3259, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/piel/development/odemis/src/odemis/gui/cont/tabs.py", line 1931, in display_new_data
    scont = self._stream_bar_controller.addStream(s, add_to_view=True)
  File "/home/piel/development/odemis/src/odemis/gui/cont/streams.py", line 1644, in addStream
    return self._add_stream(stream, **kwargs)
  File "/home/piel/development/odemis/src/odemis/gui/cont/streams.py", line 1675, in _add_stream
    v.addStream(stream)
  File "/home/piel/development/odemis/src/odemis/gui/model/__init__.py", line 1437, in addStream
    stream = self._projection_klass(stream)
  File "/home/piel/development/odemis/src/odemis/acq/stream/_projection.py", line 675, in __init__
    self.stream.selectionWidth.subscribe(self._on_selected_width)
AttributeError: 'StaticCLStream' object has no attribute 'selectionWidth'

=> Rename the viewport, and remove CLStream as "compatible".