driver zeiss: Fix finding device on Python 3
GetVersion() returned bytes (on Python 3), which caused error when
comparing the string searched. It also caused a tiny bit wrong hwVersion
attribute.

This caused such error at startup:
  File "/usr/lib/python3/dist-packages/odemis/driver/zeiss.py", line 84, in __init__
    self._port, self._idn = self._findDevice(port)  # sets ._serial and ._file
  File "/usr/lib/python3/dist-packages/odemis/driver/zeiss.py", line 187, in _findDevice
    if not "smartsem" in idn.lower():
TypeError: a bytes-like object is required, not 'str'