place the external ConsoleClient packages into a try except block to avoid possible errors due to missing package. (#2404)
The error we were getting when we start the odemis is:
ModuleNotFoundError: No module named 'ConsoleClient'