util img findOptimalRange: handle better empty histogram
Very corner case. Still happened sometimes, causing such traces:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odemis/model/_vattributes.py", line 97, in notify
    l(v)
  File "/usr/lib/python2.7/dist-packages/odemis/util/weak.py", line 37, in __call__
    return self.f(ins, *arg, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odemis/acq/stream/_base.py", line 969, in _onOutliers
    self._recomputeIntensityRange()
  File "/usr/lib/python2.7/dist-packages/odemis/acq/stream/_base.py", line 974, in _recomputeIntensityRange
    self.auto_bc_outliers.value / 100)
  File "/usr/lib/python2.7/dist-packages/odemis/util/img.py", line 111, in findOptimalRange
    nval = cum_hist[-1]
IndexError: index -1 is out of bounds for axis 0 with size 0