gui cont tools: fix failure to insert an unknown tool on 2D toolbar
Because there were 2 for-loops, the break doesn't work (as expected).
So it'd always think that it didn't find a position, causing such
failure:
  File "/home/piel/development/odemis/src/odemis/gui/cont/tabs.py", line 416, in __init__
    self.tb.add_tool(TOOL_AUTO_FOCUS, self.tab_data_model.autofocus_active)
  File "/home/piel/development/odemis/src/odemis/gui/cont/tools.py", line 225, in add_tool
    self._add_mode_tool(tooltype, tool_id, handler)
  File "/home/piel/development/odemis/src/odemis/gui/cont/tools.py", line 233, in _add_mode_tool
    btn = self._add_button(ImageToggleButton, tooltype.icon, tooltype.tooltip)
  File "/home/piel/development/odemis/src/odemis/gui/cont/tools.py", line 287, in _add_button
    raise ValueError("No more space in toolbar")
ValueError: No more space in toolbar

=> Use itertool.product() to represent the 2 loops into a single for.

Also clean-up a little bit the code. Especially, avoid to use an
attribute which is only temporarily correct.