driver andorshrk: Fix flip mirror move on SR-303
commit de42c526690 (explicitely store the focus for each grating/output)
always stored/restore the focus. However, that doesn't work if the hardware
doesn't have a focus. In such case any move of the flipper would fail with:
ShamrockError: Call to ShamrockGetFocusMirror failed with error 20201: COMMUNICATION ERROR

In practice, this happened on the SR303, if it had multiple output ports.

=> Check the hardware has a focus before storing/restoring the position.