[fix] xt_client failed to start if xtadapter doesn't have set_raw_coordinate_system()
Since v1.12.0, xtadapter provides set_raw_coordinate_system().
If connecting to older version, xt_client should just be fine, and
assume the raw coordinate system is disabled. However, when the method
doesn't exists, an AttributeError is raised (not an OSError, which
happen when the call in XTLib fails).
=> Also handle AttributeError.

This fixes such errors:
2024-09-25 14:51:17,276	INFO	main:292:	Remote exception Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Pyro4/core.py", line 861, in handleRequest
    data=method(*vargs, **kwargs)   # this is the actual method call to the Pyro object
  File "/home/meteor/development/odemis/src/odemis/model/_core.py", line 281, in instantiate
    return self.daemon.instantiate(klass, kwargs)
  File "/home/meteor/development/odemis/src/odemis/model/_core.py", line 362, in instantiate
    comp = klass(**kwargs)
  File "/home/meteor/development/odemis/src/odemis/driver/xt_client.py", line 280, in __init__
    self._stage = Stage(parent=self, daemon=daemon, **ckwargs)
  File "/home/meteor/development/odemis/src/odemis/driver/xt_client.py", line 2219, in __init__
    self._switch_coordinate_system(raw_coordinates)
  File "/home/meteor/development/odemis/src/odemis/driver/xt_client.py", line 2247, in _switch_coordinate_system
    self.parent.set_raw_coordinate_system(False)
  File "/home/meteor/development/odemis/src/odemis/driver/xt_client.py", line 388, in set_raw_coordinate_system
    self.server.set_raw_coordinate_system(raw_coordinates)
  File "/usr/lib/python3/dist-packages/Pyro5/client.py", line 97, in __getattr__
    raise AttributeError("remote object '%s' has no exposed attribute or method '%s'" % (self._pyroUri, name))
AttributeError: remote object 'PYRO:Microscope@192.168.6.1:4242' has no exposed attribute or method 'set_raw_coordinate_system'