Bug fix testcases: need to wait a bit until image is generated and then try to export
Note: I was not able to reproduce the last error.

==================================================================================================

SPECTRUM EXPORT

==================================================================================================

Running /home/winkler/development/odemis/src/odemis/gui/util/test/img_test.py...

ERROR: test_spectrum_ready (__main__.TestSpectrumExport)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/winkler/development/odemis/src/odemis/gui/util/test/img_test.py", line 338, in test_spectrum_ready

    exported_data = img.spectrum_to_export_data(proj, False)

  File "/home/winkler/development/odemis/src/odemis/gui/util/img.py", line 1221, in spectrum_to_export_data

    raise LookupError("No pixel selected to pick a spectrum")

LookupError: No pixel selected to pick a spectrum

======================================================================

ERROR: test_spectrum_temporal (__main__.TestSpectrumExport)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/winkler/development/odemis/src/odemis/gui/util/test/img_test.py", line 354, in test_spectrum_temporal

    exported_data = img.chronogram_to_export_data(proj, False)

  File "/home/winkler/development/odemis/src/odemis/gui/util/img.py", line 1343, in chronogram_to_export_data

    raise LookupError("No pixel selected to pick a chronogram")

LookupError: No pixel selected to pick a chronogram

======================================================================

ERROR: test_line_ready (__main__.TestSpectrumLineExport)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/winkler/development/odemis/src/odemis/gui/util/test/img_test.py", line 459, in test_line_ready

    exported_data = img.line_to_export_data(proj, False)

  File "/home/winkler/development/odemis/src/odemis/gui/util/img.py", line 1459, in line_to_export_data

    raise LookupError("No line selected to pick a spectrum")

LookupError: No line selected to pick a spectrum

======================================================================

ERROR: test_simple (__main__.TestWxImage2NDImage)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/winkler/development/odemis/src/odemis/gui/util/test/img_test.py", line 59, in test_simple

    wximage = wx.Image(*size) # black RGB

  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 2882, in __init__

    _core_.Image_swiginit(self,_core_.new_Image(*args, **kwargs))

TypeError: String or Unicode type required

----------------------------------------------------------------------

Ran 26 tests in 17.268s