driver andorshrk: ensure getPixelToWavelength() cannot run at the same time as an axis move
There were two issues:
 * When changing to a mirror grating, the wavelength is set to 0. That should
   be concidered atomic from the point of view of getPixelToWavelength()
   => protect grating move with ._px2wl_lock
 * In case of fallback to internal calculation, the call to GetGratingInfo() could
   actually run while the move happens, and this would cause havoc in the communication
   with the hardware.
   => use ._hw_access lock around every call.

This could cause issues like this:
2019-02-04 18:13:57,416 (andorshrk) ERROR: Failed to compute pixel->wavelength (cw = 400.000000 nm)
Traceback (most recent call last):
  File "/home/sparc/development/odemis/src/odemis/driver/andorshrk.py", line 1308, in getPixelToWavelength
    return self._FallbackGetPixelToWavelength(npixels, pxs)
  File "/home/sparc/development/odemis/src/odemis/driver/andorshrk.py", line 1333, in _FallbackGetPixelToWavelength
    gl = self.GetGratingInfo(gid)[0]  # lines/meter
  File "/home/sparc/development/odemis/src/odemis/driver/andorshrk.py", line 736, in GetGratingInfo
    byref(Lines), Blaze, byref(Home), byref(Offset))
  File "/home/sparc/development/odemis/src/odemis/driver/andorshrk.py", line 128, in at_errcheck
    (func.__name__, result, errmsg.value))
ShamrockError: Call to ShamrockGetGratingInfo failed with error 20267: PARAMETER 2 INVALID
2019-02-04 18:13:57,422 (andorshrk) ERROR: Failure during move of axis grating
Traceback (most recent call last):
  File "/home/sparc/development/odemis/src/odemis/driver/andorshrk.py", line 1450, in _doMultipleActions
    func(*args)
  File "/home/sparc/development/odemis/src/odemis/driver/andorshrk.py", line 1510, in _doSetGrating
    self._restoreFocus()
  File "/home/sparc/development/odemis/src/odemis/driver/andorshrk.py", line 1270, in _restoreFocus
    op = self.GetFlipperMirror(OUTPUT_FLIPPER)
  File "/home/sparc/development/odemis/src/odemis/driver/andorshrk.py", line 1151, in GetFlipperMirror
    self._dll.ShamrockGetFlipperMirror(self._device, flipper, byref(port))
  File "/home/sparc/development/odemis/src/odemis/driver/andorshrk.py", line 128, in at_errcheck
    (func.__name__, result, errmsg.value))
ShamrockError: Call to ShamrockGetFlipperMirror failed with error 20201: COMMUNICATION ERROR