[fix] missing extend arg when loading streams via cli
Fixes an error introduced in [[MSD-350][feat] Ensure pyramidal tiff on import](https://github.com/delmic/odemis/commit/3a99f3269ffcb0ce0fb9a0d0f7ad019aa9eca8b4) on  Jun 8, 2026. Initial development focused solely on importing files via the GUI tab interfaces. But there is in fact another way of importing data, and that is via the `--file` argument of the Odemis GUI CLI. Reproduction: `odemis-gui --standalone --file <filepath>`. Stack trace:

```
18:30:13 ERROR   main           : Traceback (most recent call last):
  File "/home/piel/.local/lib/python3.12/site-packages/wx/core.py", line 2338, in Notify
    self.notify()
  File "/home/piel/.local/lib/python3.12/site-packages/wx/core.py", line 3550, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/piel/development/odemis/src/odemis/gui/cont/tabs/stream_load_mixin.py", line 80, in load_data
    self.load_streams(data, filename=filename, **kwargs)
  File "/usr/lib/python3/dist-packages/decorator.py", line 231, in fun
    args, kw = fix(args, kw, sig)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/decorator.py", line 203, in fix
    ba = sig.bind(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/inspect.py", line 3212, in _bind
    raise TypeError('missing a required argument: {arg!r}'. \
TypeError: missing a required argument: 'extend'
```