gui cont streams: Fix zIndex -> zPos mapping
The zPos range had been fixed (in the gui.model), but then the stream panel
was incorrectly connected.

It caused such error when setting to zIndex 0:
2018-12-10 16:57:36,171 ERROR   log:41: Subscriber <odemis.util.weak.WeakMethodBound object at 0x7f1cf5421d50> raised exception when receiving value 0
Traceback (most recent call last):
  File "/home/piel/development/odemis/src/odemis/model/_vattributes.py", line 100, in notify
    l(v)
  File "/home/piel/development/odemis/src/odemis/util/weak.py", line 37, in __call__
    return self.f(ins, *arg, **kwargs)
  File "/home/piel/development/odemis/src/odemis/gui/cont/streams.py", line 445, in _on_z_index
    self.tab_data_model.zPos.value = zstart + zstep * zIndex
  File "/home/piel/development/odemis/src/odemis/model/_vattributes.py", line 200, in _set_value
    self._check(value) # we allow the setter to even put illegal value, it's the master
  File "/home/piel/development/odemis/src/odemis/model/_vattributes.py", line 1027, in _check
    Continuous._check(self, value)
  File "/home/piel/development/odemis/src/odemis/model/_vattributes.py", line 916, in _check
    raise IndexError(msg % (value, start, end))
IndexError: Trying to assign value '(1.3086999999999999e-05,)' outside of the range (1.3186999999999998e-05,)->(2.4987e-05,).