[fix] TestMimasMove cancel test failure
Disable the checks on stage position in the event of cancelling the stage movement to loading in mimas, because due to the rough simulator, it's very timing dependent, and sometimes the test case fails.

It showed up like that:
Running /home/testing/development/odemis/src/odemis/acq/test/move_test.py:
FAILED move_test.py::TestMimasMove::test_cancel_loading - AssertionError: 0 == 0