Fix Bug: In alignment tab for streak camera calibration, the range of the histogram values was set to default min/max values. However, if range of intensity counts for data is smaller or out of range for histogram range, then it failed. Use clip method of VA to make sure a useful intensityRange is set.
  File "/usr/lib/python2.7/dist-packages/wxPython-4.0.4-py2.7-linux-x86_64.egg/wx/core.py", line 3259, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/sparc/development/odemis/src/odemis/gui/cont/tabs.py", line 3613, in _onAlignMode
    self._ts_stream.intensityRange.value = (100, 1000)  # default range
  File "/home/sparc/development/odemis/src/odemis/model/_vattributes.py", line 1142, in _set_value
    VigilantAttribute._set_value(self, value, **kwargs)
  File "/home/sparc/development/odemis/src/odemis/model/_vattributes.py", line 200, in _set_value
    self._check(value) # we allow the setter to even put illegal value, it's the master
  File "/home/sparc/development/odemis/src/odemis/model/_vattributes.py", line 1151, in _check
    Continuous._check(self, value)
  File "/home/sparc/development/odemis/src/odemis/model/_vattributes.py", line 916, in _check
    raise IndexError(msg % (value, start, end))
IndexError: Trying to assign value '(100, 1000)' outside of the range (322, 322)->(833, 833)