driver omicronxx: Report external interlock error and log errors more thoroughly
If the external interlock is opened, reset the controller will not help => just inform the user to close it back.

Also, it seems that it's not possible to reset a sub device (which makes sense), so always reset the master device.

Also read and report the latched error, which is the error that triggered the current error state (as it may have disappeared).

Also extend the simulator code to test the error path.

Example of session before, which caused havoc:
DEBUG: Sending: '?GAS\r'
DEBUG: Received: '!GAS00D0'
DEBUG: Device (on port /dev/ttyFTDI0) status = 0xD0
DEBUG: Sending: '?GFw\r'
DEBUG: Received: '!GFwLEDHUB\xa720\xa71.08'
DEBUG: Sending: '?GSI\r'
DEBUG: Received: '!GSI[m53]0\xa70'
DEBUG: Sending: '?GSI[1]\r'
DEBUG: Received: '!GSI[1]385\xa71400'
DEBUG: Sending: '?GSN[1]\r'
DEBUG: Received: '!GSN[1]1602-47'
DEBUG: Sending: '?GAS[1]\r'
DEBUG: Received: '!GAS[1]00C9'
DEBUG: Device (on port /dev/ttyFTDI0) status = 0xC9
DEBUG: Sending: '?GFB[1]\r'
DEBUG: Received: '!GFB[1]0201'
INFO: Device (on port /dev/ttyFTDI0) reports error 201, will reset it
DEBUG: Sending: '?RsC[1]\r'
DEBUG: Received: '?RsC'
IOError: Answer prefix (!) not found.